### ISSUE TITLE
Applauncher is zope.event dependent

### ISSUE THREAD

**Issue by luapmartin** [applauncher-team/applauncher#7]
Hi,

One possible drawback of the applauncher is that the actual event dispatcher system in included by default (zope.event).
It could be better to abstract the event dispatcher system from the Kernel Core Module.
Then the event dispatcher system can be wrapped behind simples methods (notifications and handlers) and changed in respect of the App requirements or developers preferences.

Regards,
Paul

**Comment by luapmartin** [comment]
Adding here a pointer to a Mediator Pattern implementation in python (adapted from symphony php framework the "event-dispatcher" component.) : https://github.com/Komtet/mediator 

Also adding this Pattern for large scale apps : combining modules (bundles here) with the "mediador" pattern behind "facade" to abstract the relation between modules and ensure re-usability : https://addyosmani.com/largescalejavascript/

**Comment by maxpowel** [comment]
Yea, nice article. The bundles contain the modules and the facades. Combined with dependency injection you can interact between bundles without knowing anything about them (which is one of the goals of the article you mentioned).

I really wanted to build something like mediator, but didnt have time. I'm going to check this library

**Comment by maxpowel** [comment]
These changes break backwards compatibility so every bundle that uses eventsmust be adapted to this new mediator feature

**Comment by luapmartin** [comment]
see #11

**Comment by maxpowel** [comment]
Fixed
