### ISSUE TITLE
ThreadPoolExecutor missing initialization parameter

### ISSUE THREAD

**Issue by luapmartin** [applauncher-team/applauncher#8]
Hi,

The ThreadPoolExecutor needs the amount of worker to be set by default (can be read then from config file to use parallel workers if needed) :

from the kernel.py file : `self.thread_pool = concurrent.futures.ThreadPoolExecutor()`

from the Python documentation : `class concurrent.futures.ThreadPoolExecutor(max_workers=None, thread_name_prefix='')`

https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor

here is the error message I got :

```
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    with Kernel(Environments.DEVELOPMENT, bundle_list) as k:
  File "venv/lib/python3.4/site-packages/applauncher/kernel.py", line 45, in __init__
    self.thread_pool = concurrent.futures.ThreadPoolExecutor()
TypeError: __init__() missing 1 required positional argument: 'max_workers'
```

setting up the max_workers=1 it goes well. ( #9 )

**Comment by maxpowel** [comment]
Fixed!
